#!/usr/bin/env python

import os, sys, tempfile, shutil, subprocess, textwrap

from zeroinstall.injector.config import load_config
from zeroinstall.injector import gpg

config = load_config()
uri, = sys.argv[1:]
iface = config.iface_cache.get_interface(uri)
deb_name = iface.get_name().lower().replace(' ', '-')

print iface.get_name()

desktop = """[Desktop Entry]
# This file was generated by 02deb.
# See the Zero Install project for details: http://0install.net
Type=Application
Version=1.0
Name={name}
Comment={comment}
Exec={launch} -- {iface} %f
Categories=Application
""".format(name = iface.get_name(),
	   comment = iface.summary,
	   launch = '/usr/bin/0launch',
	   iface = uri)

sig, = config.iface_cache.get_cached_signatures(uri)[:1]
key = gpg.load_key(sig.fingerprint)

desc_paras = ('Description: ' + iface.description).split('\n\n')
wrapped = [textwrap.wrap(para) for para in desc_paras]
desc_lines = []
for para in wrapped:
	desc_lines += [' ' + (line or '.') for line in para]
description = '\n'.join(desc_lines)[1:]

control = """Package: {deb_name}-launcher
Version: 1-1
Section: misc
Priority: optional
Architecture: all
Depends: zeroinstall-injector (>= 0.30)
Installed-Size: 1
Maintainer: {author}
{description}
 .
 Note: This is a launcher package; the actual program will be run using
 Zero Install.
 .
""".format(deb_name = deb_name,
	   author = key.name,
	   description = description)

d = tempfile.mkdtemp(prefix = '02deb-')
try:
	bin_dir = d + '/usr/bin'
	apps_dir = d + '/usr/share/applications'
	deb_dir = d + '/DEBIAN'
	os.makedirs(bin_dir)
	os.makedirs(apps_dir)
	os.makedirs(deb_dir)

	s = open(apps_dir + '/' + deb_name + '.desktop', 'w')
	s.write(desktop)
	s.close()

	s = open(deb_dir + '/control', 'w')
	s.write(control)
	s.close()

	subprocess.check_call(['fakeroot', 'dpkg-deb', '--build', '--', d, deb_name + '.deb'])
finally:
	shutil.rmtree(d)
