# Copyright (C) 2011, Thomas Leonard
# Visit http://0install.net for details.

def make_desktop_file(iface, icon=None):
	return """[Desktop Entry]
	# This file was generated by 0bootstrap.
	# See the Zero Install project for details: http://0install.net
	Type=Application
	Version=1.0
	Name={name}
	Comment={comment}
	Exec={launch} -- {iface} %f
	Icon={icon}
	Categories=Application
	""".format(name = iface.get_name(),
		   comment = iface.summary,
		   launch = '/usr/bin/0launch',
		   icon = icon or "",
		   iface = iface.uri)
